"""Append-only dialog journal data layer."""

from jarvis.journal.corpus import (
    CURRENT_HISTORY_CORPUS_SCHEMA_VERSION,
    HISTORY_READ_MAX_BATCH_RANGES,
    HISTORY_READ_MAX_EVENTS_PER_RANGE,
    HISTORY_READ_MAX_TOTAL_EVENTS,
    HISTORY_SEARCH_MAX_RESULTS,
    HistoryBatchRead,
    HistoryBatchReadStatus,
    HistoryCorpusEvent,
    HistoryCorpusRepository,
    HistoryCorpusSchemaError,
    HistoryEventRange,
    HistoryEventRangeRead,
    HistoryEventRangeStatus,
    HistoryEventRead,
    HistoryEventReadStatus,
    HistoryEventRefsRead,
    HistoryEventRefsReadStatus,
    HistorySearchHit,
    HistorySearchOrder,
    HistorySearchRequest,
    HistorySearchResult,
    HistorySearchStatus,
    HistorySessionMetadata,
    HistorySessionRead,
    HistorySessionReadStatus,
)
from jarvis.journal.events import (
    JournalEvent,
    JournalEventAppended,
    JournalEventRecord,
    JournalEventRef,
    TurnOutcome,
    new_session_id,
)
from jarvis.journal.lifecycle import (
    CorpusHistoryProjection,
    HistoryProjectionConsistencyError,
    HistoryProjectionLifecycle,
    HistoryProjectionStatus,
    JournalHistoryService,
    SemanticProjectionBackendIdentity,
    SemanticProjectionState,
    UnavailableSemanticHistoryProjection,
)
from jarvis.journal.recorder import JournalRecorder
from jarvis.journal.search import JournalSearchHit, JournalSearchIndex
from jarvis.journal.store import (
    JournalReplay,
    JournalSessionSummary,
    JournalSessionUsage,
    JournalStore,
    JournalUsage,
)

__all__ = [
    "CURRENT_HISTORY_CORPUS_SCHEMA_VERSION",
    "HISTORY_READ_MAX_BATCH_RANGES",
    "HISTORY_READ_MAX_EVENTS_PER_RANGE",
    "HISTORY_READ_MAX_TOTAL_EVENTS",
    "HISTORY_SEARCH_MAX_RESULTS",
    "CorpusHistoryProjection",
    "HistoryBatchRead",
    "HistoryBatchReadStatus",
    "HistoryCorpusEvent",
    "HistoryCorpusRepository",
    "HistoryCorpusSchemaError",
    "HistoryEventRange",
    "HistoryEventRangeRead",
    "HistoryEventRangeStatus",
    "HistoryEventRead",
    "HistoryEventReadStatus",
    "HistoryEventRefsRead",
    "HistoryEventRefsReadStatus",
    "HistoryProjectionConsistencyError",
    "HistoryProjectionLifecycle",
    "HistoryProjectionStatus",
    "HistorySearchHit",
    "HistorySearchOrder",
    "HistorySearchRequest",
    "HistorySearchResult",
    "HistorySearchStatus",
    "HistorySessionMetadata",
    "HistorySessionRead",
    "HistorySessionReadStatus",
    "JournalEvent",
    "JournalEventAppended",
    "JournalEventRecord",
    "JournalEventRef",
    "JournalHistoryService",
    "JournalRecorder",
    "JournalReplay",
    "JournalSearchHit",
    "JournalSearchIndex",
    "JournalSessionSummary",
    "JournalSessionUsage",
    "JournalStore",
    "JournalUsage",
    "SemanticProjectionBackendIdentity",
    "SemanticProjectionState",
    "TurnOutcome",
    "UnavailableSemanticHistoryProjection",
    "new_session_id",
]
