// Static-text dictionary for the web UI surfaces (story-v1.2.11).
//
// Loaded before transport.js/app.js/touchstrip.js so every layer can look
// up text through uiString(). The active language starts as English (the
// project default) and is switched by applyUiLanguage() when the engine
// snapshot delivers state.ui_language - the Python side owns the setting
// ([ui].language in config.py), this file only renders it.
//
// HTML elements carry data-i18n="key" (text content) or
// data-i18n-title="key" (title attribute); applyUiLanguage() re-stamps
// them all, so the pre-transport English markup and the post-snapshot
// language always agree with one dictionary, never two copies.

const UI_STRINGS = {
  en: {
    locality_local: "Local",
    locality_external: "External backend",
    data_source_local_only: "Local sources",
    data_source_lan: "LAN source used",
    data_source_internet: "Internet source used",
    data_source_unknown: "Tool boundary unknown",
    mcp_title: "External tools (MCP)",
    mcp_off: "Off",
    mcp_connecting: "Connecting",
    mcp_on: "On",
    mcp_degraded: "Degraded",
    mcp_disconnecting: "Disconnecting",
    mcp_enable: "Enable",
    mcp_disable: "Disable",
    mcp_no_tools: "No tools available",
    mcp_tool_available: "available",
    mcp_tool_unavailable: "unavailable",
    chip_model: "Model",
    chip_microphone: "Microphone",
    chip_tts: "TTS",
    chip_memory: "Memory",
    chip_vision: "Vision",
    modules_title: "Modules",
    last_request_title: "Last request to model",
    last_request_audio: "Voice",
    last_request_screenshot: "Screenshot",
    last_request_clipboard: "Clipboard",
    last_request_text_input: "Typed message",
    last_request_attachment_image: "Attached image",
    last_request_attachment_audio: "Attached audio",
    last_request_attachment_text: "Attached text",
    chip_reset_backend: "Request model/backend reset",
    chip_reset_microphone: "Request microphone reset",
    chip_reset_tts: "Request TTS reset",
    chip_reset_memory: "Request memory reset",
    chip_reset_vision: "Request vision/screen reset",
    think_title: "Thinking mode",
    think_status_off: "Fastest, without reasoning",
    think_status_low: "Light reasoning - a little slower",
    think_status_medium: "Deeper reasoning - noticeably slower",
    think_status_high: "Maximum reasoning - slowest, most thorough",
    reasoning_off: "Off",
    reasoning_low: "Low",
    reasoning_medium: "Medium",
    reasoning_high: "High",
    btn_settings: "⚙ Settings",
    btn_reset_context: "Reset context",
    btn_shutdown: "Shut down",
    confirm_reset_text: "The dialog and current context will be deleted. This cannot be undone.",
    confirm_shutdown_text: "Jarvis will be stopped. You will need to start the process again.",
    btn_cancel: "Cancel",
    btn_confirm_reset: "Reset",
    btn_confirm_shutdown: "Shut down",
    config_model_label: "Model",
    config_microphone_label: "Microphone",
    config_ui_language_label: "Interface language",
    config_tts_section_label: "Speech synthesis (TTS)",
    config_tts_custom_label: "Configure per-language voices",
    config_tts_route_label: "Voice ({lang})",
    config_tts_default_value: "engine default",
    config_tts_false_value: "false",
    config_tts_true_value: "true",
    config_tts_field_model: "Model or model path",
    config_tts_field_language: "Model language",
    config_tts_field_speaker: "Speaker",
    config_tts_field_sample_rate: "Sample rate",
    config_tts_field_put_accent: "Add accents",
    config_tts_field_put_yo: "Use yo",
    config_tts_field_config_path: "Config path",
    config_tts_field_use_cuda: "Use CUDA",
    config_tts_field_espeak_data_dir: "eSpeak data directory",
    config_tts_field_download_dir: "Piper data directory",
    config_tts_field_speaker_id: "Speaker ID",
    config_tts_field_length_scale: "Length scale",
    config_tts_field_noise_scale: "Noise scale",
    config_tts_field_noise_w_scale: "Noise width scale",
    config_tts_field_normalize_audio: "Normalize audio",
    config_tts_field_volume: "Volume",
    config_vad_section_label: "Voice detection (VAD)",
    config_vad_threshold_label: "Sensitivity threshold",
    config_vad_max_chunk_label: "Max phrase length, s",
    config_vad_end_pause_label: "End-of-request pause, s",
    config_vad_cooldown_label: "Resume cooldown, s",
    btn_apply: "Apply",
    pending_restart_text: "Changes saved - restart Jarvis to apply.",
    default_microphone_option: "(system default microphone)",
    log_title: "System events",
    log_sub: "engine log - real time",
    log_empty: "No events yet",
    legend_info: "info",
    legend_active: "active",
    legend_warn: "warning",
    legend_error: "error",
    vision_preview_hidden: "preview hidden (Hidden)",
    view_console: "Console",
    view_journal: "Journal",
    journal_sessions_title: "Sessions",
    journal_no_sessions: "No sessions yet",
    journal_no_selection: "Select a session on the left",
    journal_empty_feed: "No turns in this session",
    journal_hidden_placeholder: "Journal hidden (Hidden)",
    journal_source_voice: "Voice",
    journal_source_text: "Clipboard",
    journal_source_dock: "Typed",
    journal_source_attachment: "Attachment",
    journal_source_assistant: "Jarvis",
    journal_source_fork: "Fork",
    journal_source_context: "Context",
    journal_audio_play: "Play",
    journal_audio_pause: "Pause",
    journal_search_label: "Search Jarvis answers",
    journal_search_placeholder: "Search exact words or prefixes",
    journal_search_date_from: "From",
    journal_search_date_to: "To",
    journal_search_clear: "Clear",
    journal_search_no_results: "No matching Jarvis answers",
    journal_input_placeholder: "Message Jarvis",
    journal_input_send: "Send",
    journal_input_busy: "Jarvis is busy. Your text was kept.",
    journal_input_hidden: "Journal is hidden. Your text was kept.",
    journal_input_empty: "Write a message first.",
    journal_input_over_limit: "Message is over {max} characters. Shorten it and try again.",
    journal_input_failed: "Message was not sent. Your text was kept.",
    journal_input_sent: "Sent",
    journal_attach: "Attach",
    journal_attach_title: "Attach files",
    journal_drop_target: "Drop files here",
    journal_attachment_pending: "Ready",
    journal_attachment_remove: "Remove file",
    journal_attachment_status_accepted: "Accepted",
    journal_attachment_status_warning: "Warning",
    journal_attachment_status_rejected: "Rejected",
    journal_attachment_class_audio: "Audio",
    journal_attachment_class_image: "Image",
    journal_attachment_class_text: "Text",
    journal_attachment_class_unknown: "File",
    journal_copy_answer: "Copy answer",
    journal_copy_done: "Copied",
    journal_copy_failed: "Copy failed",
    journal_image_missing: "Image unavailable",
    journal_usage_total: "Journal: {size}",
    journal_new_context: "New context",
    journal_new_context_confirm: "Start a blank context and leave the current one?",
    journal_new_context_ready: "New context ready.",
    journal_new_context_required: "Start a new context first.",
    journal_new_context_busy: "Jarvis is busy. Try again after the current turn.",
    journal_new_context_hidden: "Journal is hidden.",
    journal_new_context_failed: "New context was not created.",
    journal_memory_open: "Memory",
    journal_memory_close: "Close",
    journal_memory_title: "Memory",
    journal_memory_note: "Changes apply from the next session start.",
    journal_memory_self_title: "self.md",
    journal_memory_self_description: "Jarvis persona and self-knowledge.",
    journal_memory_memory_title: "memory.md",
    journal_memory_memory_description: "Durable facts and standing context.",
    journal_memory_save: "Save",
    journal_memory_saved: "Saved",
    journal_memory_counter: "{chars} / {max}",
    journal_memory_over_limit: "Over the character cap.",
    journal_memory_hidden: "Journal is hidden.",
    journal_memory_load_failed: "Memory files could not be loaded.",
    journal_memory_save_failed: "Memory file was not saved.",
    journal_memory_discard_confirm: "Discard unsaved memory edits?",
    journal_session_delete: "Delete session",
    journal_session_continue: "Continue conversation",
    journal_session_active: "Current session cannot be deleted",
    journal_delete_confirm: "Delete session {title} ({size})?",
    journal_delete_failed: "Session was not deleted.",
    journal_delete_active: "Current session cannot be deleted.",
    journal_delete_not_found: "Session no longer exists.",
    journal_fork_started: "Fork started.",
    journal_fork_busy: "Jarvis is busy. Try again after the current turn.",
    journal_fork_hidden: "Journal is hidden.",
    journal_fork_unknown: "Session no longer exists.",
    journal_fork_oversize: "A single turn is over the {max} character seed budget.",
    journal_fork_failed: "Conversation was not continued.",
    journal_fork_truncated: "Seed dropped {count} older turns to fit the budget.",
    transport_no_connection: "No connection to engine",
    transport_no_token: "No UI transport token in URL",
    transport_data_error: "UI transport data error",
    strip_locality_local: "local",
    strip_locality_external: "external backend",
    strip_think_label: "Thinking",
    strip_reset_hold_hint: "hold 1s to confirm",
    strip_shutdown_hold_hint: "hold 2s to confirm",
  },
  ru: {
    locality_local: "Локально",
    locality_external: "Внешний backend",
    data_source_local_only: "Локальные источники",
    data_source_lan: "Использован источник в локальной сети",
    data_source_internet: "Использован интернет-источник",
    data_source_unknown: "Граница инструмента неизвестна",
    mcp_title: "Внешние инструменты (MCP)",
    mcp_off: "Выключено",
    mcp_connecting: "Подключение",
    mcp_on: "Включено",
    mcp_degraded: "Работает частично",
    mcp_disconnecting: "Отключение",
    mcp_enable: "Включить",
    mcp_disable: "Выключить",
    mcp_no_tools: "Нет доступных инструментов",
    mcp_tool_available: "доступен",
    mcp_tool_unavailable: "недоступен",
    chip_model: "Модель",
    chip_microphone: "Микрофон",
    chip_tts: "TTS",
    chip_memory: "Память",
    chip_vision: "Vision",
    modules_title: "Модули",
    last_request_title: "Последний запрос к модели",
    last_request_audio: "Голос",
    last_request_screenshot: "Скриншот",
    last_request_clipboard: "Буфер обмена",
    last_request_text_input: "Текстовый ввод",
    last_request_attachment_image: "Прикреплённое изображение",
    last_request_attachment_audio: "Прикреплённое аудио",
    last_request_attachment_text: "Прикреплённый текст",
    chip_reset_backend: "Запросить сброс модели/backend",
    chip_reset_microphone: "Запросить сброс микрофона",
    chip_reset_tts: "Запросить сброс TTS",
    chip_reset_memory: "Запросить сброс памяти",
    chip_reset_vision: "Запросить сброс vision/экрана",
    think_title: "Режим мышления",
    think_status_off: "Быстрее всего, без рассуждения",
    think_status_low: "Лёгкое рассуждение - немного медленнее",
    think_status_medium: "Глубокое рассуждение - заметно медленнее",
    think_status_high: "Максимальное рассуждение - самое медленное и подробное",
    reasoning_off: "Выкл",
    reasoning_low: "Низкий",
    reasoning_medium: "Средний",
    reasoning_high: "Высокий",
    btn_settings: "⚙ Настройки",
    btn_reset_context: "Сбросить контекст",
    btn_shutdown: "Завершить работу",
    confirm_reset_text: "Диалог и текущий контекст будут удалены. Отменить нельзя.",
    confirm_shutdown_text: "Jarvis будет остановлен. Потребуется запустить процесс заново.",
    btn_cancel: "Отмена",
    btn_confirm_reset: "Сбросить",
    btn_confirm_shutdown: "Завершить",
    config_model_label: "Модель",
    config_microphone_label: "Микрофон",
    config_ui_language_label: "Язык интерфейса",
    config_tts_section_label: "Синтез речи (TTS)",
    config_tts_custom_label: "Настроить голоса по языкам",
    config_tts_route_label: "Голос ({lang})",
    config_tts_default_value: "по умолчанию движка",
    config_tts_false_value: "нет",
    config_tts_true_value: "да",
    config_tts_field_model: "Модель или путь к модели",
    config_tts_field_language: "Язык модели",
    config_tts_field_speaker: "Голос",
    config_tts_field_sample_rate: "Частота дискретизации",
    config_tts_field_put_accent: "Расставлять ударения",
    config_tts_field_put_yo: "Использовать ё",
    config_tts_field_config_path: "Путь к конфигурации",
    config_tts_field_use_cuda: "Использовать CUDA",
    config_tts_field_espeak_data_dir: "Каталог данных eSpeak",
    config_tts_field_download_dir: "Каталог данных Piper",
    config_tts_field_speaker_id: "ID голоса",
    config_tts_field_length_scale: "Масштаб длительности",
    config_tts_field_noise_scale: "Масштаб шума",
    config_tts_field_noise_w_scale: "Масштаб ширины шума",
    config_tts_field_normalize_audio: "Нормализовать звук",
    config_tts_field_volume: "Громкость",
    config_vad_section_label: "Детекция голоса (VAD)",
    config_vad_threshold_label: "Порог чувствительности",
    config_vad_max_chunk_label: "Макс. длина фразы, с",
    config_vad_end_pause_label: "Пауза конца запроса, с",
    config_vad_cooldown_label: "Пауза перед возобновлением, с",
    btn_apply: "Применить",
    pending_restart_text: "Изменения сохранены - перезапустите Jarvis, чтобы применить.",
    default_microphone_option: "(системный микрофон по умолчанию)",
    log_title: "События системы",
    log_sub: "engine log - реальное время",
    log_empty: "Пока нет событий",
    legend_info: "инфо",
    legend_active: "активно",
    legend_warn: "предупреждение",
    legend_error: "ошибка",
    vision_preview_hidden: "превью скрыто (Hidden)",
    view_console: "Консоль",
    view_journal: "Журнал",
    journal_sessions_title: "Сессии",
    journal_no_sessions: "Пока нет сессий",
    journal_no_selection: "Выберите сессию слева",
    journal_empty_feed: "В этой сессии нет реплик",
    journal_hidden_placeholder: "Журнал скрыт (Hidden)",
    journal_source_voice: "Голос",
    journal_source_text: "Буфер обмена",
    journal_source_dock: "Ввод",
    journal_source_attachment: "Вложение",
    journal_source_assistant: "Jarvis",
    journal_source_fork: "Fork",
    journal_source_context: "Контекст",
    journal_audio_play: "Воспроизвести",
    journal_audio_pause: "Пауза",
    journal_search_label: "Поиск ответов Jarvis",
    journal_search_placeholder: "Точные слова или начала слов",
    journal_search_date_from: "С",
    journal_search_date_to: "По",
    journal_search_clear: "Очистить",
    journal_search_no_results: "Подходящих ответов Jarvis нет",
    journal_input_placeholder: "Сообщение Jarvis",
    journal_input_send: "Отправить",
    journal_input_busy: "Jarvis занят. Текст сохранён.",
    journal_input_hidden: "Журнал скрыт. Текст сохранён.",
    journal_input_empty: "Сначала напишите сообщение.",
    journal_input_over_limit: "Сообщение длиннее {max} символов. Сократите его и попробуйте снова.",
    journal_input_failed: "Сообщение не отправлено. Текст сохранён.",
    journal_input_sent: "Отправлено",
    journal_attach: "Файл",
    journal_attach_title: "Прикрепить файлы",
    journal_drop_target: "Перетащите файлы сюда",
    journal_attachment_pending: "Готово",
    journal_attachment_remove: "Убрать файл",
    journal_attachment_status_accepted: "Принято",
    journal_attachment_status_warning: "Предупреждение",
    journal_attachment_status_rejected: "Отклонено",
    journal_attachment_class_audio: "Аудио",
    journal_attachment_class_image: "Изображение",
    journal_attachment_class_text: "Текст",
    journal_attachment_class_unknown: "Файл",
    journal_copy_answer: "Скопировать ответ",
    journal_copy_done: "Скопировано",
    journal_copy_failed: "Не удалось скопировать",
    journal_image_missing: "Изображение недоступно",
    journal_usage_total: "Журнал: {size}",
    journal_new_context: "Новый контекст",
    journal_new_context_confirm: "Начать пустой контекст и выйти из текущего?",
    journal_new_context_ready: "Новый контекст готов.",
    journal_new_context_required: "Сначала начните новый контекст.",
    journal_new_context_busy: "Jarvis занят. Попробуйте после текущего ответа.",
    journal_new_context_hidden: "Журнал скрыт.",
    journal_new_context_failed: "Новый контекст не создан.",
    journal_memory_open: "Память",
    journal_memory_close: "Закрыть",
    journal_memory_title: "Память",
    journal_memory_note: "Изменения применятся со следующей сессии.",
    journal_memory_self_title: "self.md",
    journal_memory_self_description: "Персона Jarvis и знание о себе.",
    journal_memory_memory_title: "memory.md",
    journal_memory_memory_description: "Долговременные факты и постоянный контекст.",
    journal_memory_save: "Сохранить",
    journal_memory_saved: "Сохранено",
    journal_memory_counter: "{chars} / {max}",
    journal_memory_over_limit: "Превышен лимит символов.",
    journal_memory_hidden: "Журнал скрыт.",
    journal_memory_load_failed: "Не удалось загрузить файлы памяти.",
    journal_memory_save_failed: "Файл памяти не сохранён.",
    journal_memory_discard_confirm: "Отбросить несохранённые правки памяти?",
    journal_session_delete: "Удалить сессию",
    journal_session_continue: "Продолжить разговор",
    journal_session_active: "Текущую сессию нельзя удалить",
    journal_delete_confirm: "Удалить сессию {title} ({size})?",
    journal_delete_failed: "Сессия не удалена.",
    journal_delete_active: "Текущую сессию нельзя удалить.",
    journal_delete_not_found: "Сессия больше не существует.",
    journal_fork_started: "Новая сессия создана.",
    journal_fork_busy: "Jarvis занят. Попробуйте после текущего ответа.",
    journal_fork_hidden: "Журнал скрыт.",
    journal_fork_unknown: "Сессия больше не существует.",
    journal_fork_oversize: "Одна реплика длиннее бюджета seed: {max} символов.",
    journal_fork_failed: "Не удалось продолжить разговор.",
    journal_fork_truncated: "Seed отбросил старые реплики, чтобы войти в бюджет: {count}.",
    transport_no_connection: "Нет связи с engine",
    transport_no_token: "Нет токена UI transport в URL",
    transport_data_error: "Ошибка данных UI transport",
    strip_locality_local: "локально",
    strip_locality_external: "внешний backend",
    strip_think_label: "Мышление",
    strip_reset_hold_hint: "удержать 1с для подтверждения",
    strip_shutdown_hold_hint: "удержать 2с для подтверждения",
  },
};

const DEFAULT_UI_LANGUAGE = "en";
let _uiLanguage = DEFAULT_UI_LANGUAGE;

function uiString(key) {
  const catalog = UI_STRINGS[_uiLanguage] || UI_STRINGS[DEFAULT_UI_LANGUAGE];
  const text = catalog[key];
  if (text === undefined) {
    throw new Error("Unknown UI string key: " + key);
  }
  return text;
}

function currentUiLanguage() {
  return _uiLanguage;
}

// Called from the snapshot/delta handlers with state.ui_language. The
// language never changes mid-session on the Python side (config is
// restart-to-apply), so in practice this runs once per connection - but
// re-stamping is idempotent either way.
function applyUiLanguage(payload) {
  const language = payload && payload.language;
  if (!Object.prototype.hasOwnProperty.call(UI_STRINGS, language)) return;
  _uiLanguage = language;
  document.documentElement.setAttribute("lang", language);
  document.querySelectorAll("[data-i18n]").forEach((element) => {
    element.textContent = uiString(element.getAttribute("data-i18n"));
  });
  document.querySelectorAll("[data-i18n-title]").forEach((element) => {
    element.title = uiString(element.getAttribute("data-i18n-title"));
  });
  document.querySelectorAll("[data-i18n-placeholder]").forEach((element) => {
    element.placeholder = uiString(element.getAttribute("data-i18n-placeholder"));
  });
}
